# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib phomstab
#' @importFrom Rcpp sourceCpp
NULL
#' This function builds, on top of an input data points, a filtration employing lazy witness complex from GUDHI package. Note that the landmarks is chosen by random subsampling and the distanceadopted is the euclidean
#'
#' param X		Input data points matrix
#' param nLandmarks	Number of landmarks adopted in lazy witness which are chosen by random subsampling
#' param maxDimension	Maximum dimesion on the constructed complex
#' param isWeak		If true the weak witness is employed, conversely, strong witness is adopted if it is false
#' param relaxed	If true the lazy witness is relaxed as shown in http://gudhi.gforge.inria.fr/doc/latest/group__witness__complex.html and alpha applies. 
#' param alpha		Parameter alpha of relaxed lazy witness
#' return		A persistence diagram
#' @export
witDiag <- function(X, nLandmarks, maxDimension, isWeak, relaxed, alpha) {
    .Call('_phomstab_witDiag', PACKAGE = 'phomstab', X, nLandmarks, maxDimension, isWeak, relaxed, alpha)
}

