// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// witDiag
Rcpp::List witDiag(const Rcpp::NumericMatrix& X, const int nLandmarks, const int maxDimension, const bool isWeak, const int relaxed, const double alpha);
RcppExport SEXP _phomstab_witDiag(SEXP XSEXP, SEXP nLandmarksSEXP, SEXP maxDimensionSEXP, SEXP isWeakSEXP, SEXP relaxedSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const int >::type nLandmarks(nLandmarksSEXP);
    Rcpp::traits::input_parameter< const int >::type maxDimension(maxDimensionSEXP);
    Rcpp::traits::input_parameter< const bool >::type isWeak(isWeakSEXP);
    Rcpp::traits::input_parameter< const int >::type relaxed(relaxedSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(witDiag(X, nLandmarks, maxDimension, isWeak, relaxed, alpha));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_phomstab_witDiag", (DL_FUNC) &_phomstab_witDiag, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_phomstab(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
